version: "2"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    
  
  node:
    image: node:16
    user: "node"
    working_dir: /home/node/app
    environment:  
      - NODE_ENV=development
    volumes:
      - ./src:/home/node/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: "npm run dev"